#!/usr/bin/env python3
"""
server.py - gRPC server for AI Demo service

This server provides a health check endpoint via gRPC.
The server listens on port 50051 by default (configurable via PORT environment variable).

Usage:
    python server.py
    or
    ./server.py
"""

import logging
import os
import re
import sys
import uuid
from concurrent import futures

import grpc

# Configure logging FIRST, before any other imports that might use logger
logging.basicConfig(
    level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Get the directory where this script is located
# Use absolute path to ensure we get the correct directory
script_path = os.path.abspath(__file__)
app_dir = os.path.dirname(script_path)

# Add app directory to Python path to allow imports
# This ensures that proto/ directory can be imported as a package
if app_dir not in sys.path:
    sys.path.insert(0, app_dir)

# Change to app directory to ensure relative imports work correctly
# This is important for Python to find the proto package
# Use absolute path to avoid issues with relative paths
os.chdir(os.path.abspath(app_dir))

# Import generated gRPC code
# These files are generated by generate_proto.sh from proto/health.proto
# They are also generated during Docker build in Dockerfile.dev
# The files are generated into proto/ directory, so we import from proto package
# proto/__init__.py is created in Dockerfile to make it a Python package

# Debug: Log current state before import
logger.debug(f"Python path: {sys.path[:3]}")
logger.debug(f"Current directory: {os.getcwd()}")
logger.debug(f"App directory: {app_dir}")

TEXT_POLICY_TERMS = {
    "spam": {"spam", "giveaway", "free money", "cheap followers"},
    "scam": {"scam", "crypto doubling", "wire transfer", "investment guaranteed"},
    "phishing": {"phishing", "password reset link", "verify your account", "login now"},
    "hate": {"hate", "slur", "racist"},
    "harassment": {"harass", "bully", "doxx"},
    "adult": {"adult", "porn", "nsfw", "sexual"},
    "violence": {"violence", "kill", "weapon", "blood"},
    "self_harm": {"self harm", "suicide", "hurt myself"},
    "copyright": {"pirated", "leaked movie", "copyright bypass"},
}

SUPPORTED_MEDIA_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".gif",
    ".mp4",
    ".webm",
    ".mov",
}


def _contains_term(text: str, term: str) -> bool:
    return bool(re.search(rf"(^|[^a-z0-9]){re.escape(term)}([^a-z0-9]|$)", text))


def _classify_text_signals(text: str) -> list[str]:
    flags: list[str] = []
    for flag, terms in TEXT_POLICY_TERMS.items():
        if any(_contains_term(text, term) for term in terms):
            flags.append(flag)
    if len(text.strip()) < 12:
        flags.append("low_quality")
    return sorted(set(flags))


def _classify_media_signals(media_url: str) -> list[str]:
    if not media_url:
        return []
    flags: list[str] = []
    lowered = media_url.lower()
    if not (lowered.startswith("http://") or lowered.startswith("https://")):
        flags.append("unsafe_link")
    path = lowered.split("?", 1)[0].split("#", 1)[0]
    if "." not in path or not any(path.endswith(ext) for ext in SUPPORTED_MEDIA_EXTENSIONS):
        flags.append("unsupported_media")
    return sorted(set(flags))


_proto_dir = os.path.join(app_dir, "proto")
_health_pb2_path = os.path.join(_proto_dir, "health_pb2.py")
_health_pb2_grpc_path = os.path.join(_proto_dir, "health_pb2_grpc.py")

try:
    if not (os.path.isfile(_health_pb2_path) and os.path.isfile(_health_pb2_grpc_path)):
        raise FileNotFoundError("health_pb2.py / health_pb2_grpc.py not found under proto/")

    # Generated *_grpc.py does `import health_pb2` (sibling module); proto/ must be on sys.path.
    if _proto_dir not in sys.path:
        sys.path.insert(0, _proto_dir)

    import health_pb2  # noqa: E402
    import health_pb2_grpc as health_pb2_grpc  # noqa: E402

    logger.info("Successfully imported gRPC code from generated proto stubs")
except (ImportError, ModuleNotFoundError, FileNotFoundError) as e:
    logger.error(f"Failed to import generated gRPC code: {e}")
    logger.error(f"Exception type: {type(e).__name__}")
    logger.error(f"Python path: {sys.path}")
    logger.error(f"Current directory: {os.getcwd()}")
    logger.error(f"App directory: {app_dir}")
    if os.path.exists(_proto_dir):
        logger.error(f"Proto directory exists: {_proto_dir}")
        try:
            logger.error(f"Files in proto directory: {os.listdir(_proto_dir)}")
        except OSError as list_error:
            logger.error(f"Could not list proto directory: {list_error}")
    logger.error("Please run ./generate_proto.sh to generate the required files")
    logger.error(
        "Or ensure Docker build completed successfully (proto files are generated during build)"
    )
    raise ImportError("gRPC stubs missing or invalid; run ./generate_proto.sh from ai_demo/") from e

# Import AI model service - communicates with a local Qwen instruct model
try:
    from services.ai_model_service import AIModelService

    _ai_service = AIModelService()
    logger.info("AIModelService ready (Qwen model will load on first Generate request)")
except ImportError as e:
    logger.warning("AIModelService not available: %s – Generate RPC will not work", e)
    _ai_service = None

from moderation_input_sanitize import sanitize_for_review


class HealthServiceServicer(health_pb2_grpc.HealthServiceServicer):
    """
    Implementation of the HealthService gRPC service.

    This class handles health check requests from clients.
    """

    def HealthCheck(self, request, context):
        """
        Health check RPC method.

        This method is called when a client requests a health check.
        It returns a success response if the server is running and ready.

        Args:
            request: HealthCheckRequest message (currently unused)
            context: gRPC context

        Returns:
            HealthCheckResponse with status="success" if server is operational
        """
        logger.info("Health check requested")

        # Return success response indicating server is running and ready
        return health_pb2.HealthCheckResponse(
            status="success", message="AI Demo service is running and ready"
        )

    def Generate(self, request, context):
        """
        AI text generation RPC method.

        Completes the given prompt using the configured local Qwen model.
        The model is loaded into memory on first call (lazy loading).

        Args:
            request: GenerateRequest with prompt and optional max_new_tokens
            context: gRPC context

        Returns:
            GenerateResponse with generated text (text field) or error message (error field)
        """
        logger.info("Generate requested, prompt length=%d", len(request.prompt or ""))
        if _ai_service is None:
            return health_pb2.GenerateResponse(
                text="",
                error="AIModelService not available (transformers/torch not installed or import failed)",
            )
        prompt = (request.prompt or "").strip()
        if not prompt:
            return health_pb2.GenerateResponse(text="", error="prompt is required")
        max_new_tokens = request.max_new_tokens if request.max_new_tokens > 0 else 50
        try:
            text = _ai_service.generate(prompt, max_new_tokens=max_new_tokens)
            return health_pb2.GenerateResponse(text=text)
        except RuntimeError as e:
            if "MODEL_LOADING" in str(e):
                logger.info("Model is still loading, returning friendly message")
                return health_pb2.GenerateResponse(
                    text="⏳ AI model sa práve načítava do pamäte (prvé spustenie po rebuilde). Skúste to prosím o pár minút znova."
                )
            logger.exception("Generate failed: %s", e)
            return health_pb2.GenerateResponse(text="", error=str(e))

    def ReviewContent(self, request, context):
        """
        Deterministic moderation recommendation used by the .NET worker (`ContentAiReviewService`).

        Pipeline:
        1. Concatenate title + body and run lightweight keyword classifiers (`_classify_text_signals`).
        2. Inspect `media_url` for scheme + extension issues (`_classify_media_signals`).
        3. Append integration-boundary flags for albums/reels (`image_analysis_boundary`, `video_analysis_boundary`)
           so downstream systems can see that a future heavyweight image/video model is not yet applied here.
        4. Split `policy_flags` (everything except boundary markers) to decide risk/decision; boundary flags alone
           never force rejection—they document future work while keeping safe content approvable.

        The backend still validates confidence/decision ranges and never auto-publishes solely on this response.
        """
        title, body, media_url = sanitize_for_review(
            request.title, request.body, request.media_url or None
        )
        text = f"{title} {body}".lower()
        flags = [*_classify_text_signals(text), *_classify_media_signals(media_url or "")]
        content_type = (request.content_type or "").strip()
        # Document future dedicated image/video models without letting these markers affect risk scoring alone.
        if content_type == "Album":
            flags.append("image_analysis_boundary")
        elif content_type == "Reel":
            flags.append("video_analysis_boundary")
        flags = sorted(set(flags))

        # Policy-driving flags exclude integration placeholders so boundary tags never flip safe items to review.
        policy_flags = [
            f for f in flags if f not in ("image_analysis_boundary", "video_analysis_boundary")
        ]
        risk_level = "low"
        decision = "approve"
        confidence = 0.86
        reason = (
            "No obvious policy, media, or quality issue was detected by the classifier fallback."
        )
        user_message = "Your content is waiting for final review."

        if policy_flags:
            high_risk_flags = {"hate", "adult", "violence", "self_harm", "unsafe_link"}
            risk_level = (
                "high" if any(flag in high_risk_flags for flag in policy_flags) else "medium"
            )
            decision = "reject" if risk_level == "high" else "needs_human_review"
            confidence = 0.88 if risk_level == "high" else 0.72
            reason = f"Potential moderation flags detected: {', '.join(sorted(set(policy_flags)))}."
            user_message = "Your content needs changes before it can be published."

        return health_pb2.ContentReviewResponse(
            decision=decision,
            confidence=confidence,
            risk_level=risk_level,
            flags=flags,
            reason=reason,
            user_message=user_message,
            model_version="qwen-advisory-classifier-v2",
            trace_id=f"ai-review-{uuid.uuid4().hex}",
        )


def serve():
    """
    Start the gRPC server.

    The server listens on the port specified by the PORT environment variable,
    or defaults to 50051 if not set.
    """
    # Get port from environment variable or use default
    port = os.getenv("PORT", "50051")
    server_address = f"0.0.0.0:{port}"

    logger.info(f"Starting gRPC server on {server_address}")

    # Create gRPC server with thread pool executor
    # max_workers: number of threads to handle concurrent requests
    # Keep-alive options: allow clients to send frequent pings (needed for
    # .NET gRPC client that sends keep-alive pings every 60s while waiting
    # for long-running AI generation requests).
    server_options = [
        ("grpc.keepalive_permit_without_calls", 1),
        ("grpc.http2.min_ping_interval_without_data_ms", 20000),
        ("grpc.http2.min_recv_ping_interval_without_data_ms", 20000),
    ]
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=10),
        options=server_options,
    )

    # Add HealthService to the server
    health_pb2_grpc.add_HealthServiceServicer_to_server(HealthServiceServicer(), server)

    # Add insecure port (for development - use TLS in production)
    server.add_insecure_port(server_address)

    # Start the server
    server.start()
    logger.info(f"gRPC server started on {server_address}")

    try:
        # Keep the server running
        server.wait_for_termination()
    except KeyboardInterrupt:
        logger.info("Shutting down server...")
        server.stop(0)
        logger.info("Server stopped")


if __name__ == "__main__":
    serve()
