#!/usr/bin/env python3
"""
server.py - gRPC server for AI Demo service

This server provides a health check endpoint via gRPC.
The server listens on port 50051 by default (configurable via PORT environment variable).

Usage:
    python server.py
    or
    ./server.py
"""

import logging
import os
import sys
from concurrent import futures

import grpc

# Configure logging FIRST, before any other imports that might use logger
logging.basicConfig(
	level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)

# Get the directory where this script is located
# Use absolute path to ensure we get the correct directory
script_path = os.path.abspath(__file__)
app_dir = os.path.dirname(script_path)

# Add app directory to Python path to allow imports
# This ensures that proto/ directory can be imported as a package
if app_dir not in sys.path:
	sys.path.insert(0, app_dir)

# Change to app directory to ensure relative imports work correctly
# This is important for Python to find the proto package
# Use absolute path to avoid issues with relative paths
os.chdir(os.path.abspath(app_dir))

# Import generated gRPC code
# These files are generated by generate_proto.sh from many_faces_proto/proto/health.proto
# They are also generated during Docker build in Dockerfile.dev
# The files are generated into proto/ directory, so we import from proto package
# proto/__init__.py is created in Dockerfile to make it a Python package

# Debug: Log current state before import
logger.debug(f"Python path: {sys.path[:3]}")
logger.debug(f"Current directory: {os.getcwd()}")
logger.debug(f"App directory: {app_dir}")

_proto_dir = os.path.join(app_dir, "proto")
_health_pb2_path = os.path.join(_proto_dir, "health_pb2.py")
_health_pb2_grpc_path = os.path.join(_proto_dir, "health_pb2_grpc.py")

try:
	if not (os.path.isfile(_health_pb2_path) and os.path.isfile(_health_pb2_grpc_path)):
		raise FileNotFoundError("health_pb2.py / health_pb2_grpc.py not found under proto/")

	# Generated *_grpc.py does `import health_pb2` (sibling module); proto/ must be on sys.path.
	if _proto_dir not in sys.path:
		sys.path.insert(0, _proto_dir)

	# noqa: E402 — imports must follow sys.path / os.chdir setup above; Ruff's import-order
	# rule would move these to the top before generated stubs exist on PYTHONPATH.
	import health_pb2  # noqa: E402
	import health_pb2_grpc as health_pb2_grpc  # noqa: E402

	logger.info("Successfully imported gRPC code from generated proto stubs")
except (ImportError, ModuleNotFoundError, FileNotFoundError) as e:
	logger.error(f"Failed to import generated gRPC code: {e}")
	logger.error(f"Exception type: {type(e).__name__}")
	logger.error(f"Python path: {sys.path}")
	logger.error(f"Current directory: {os.getcwd()}")
	logger.error(f"App directory: {app_dir}")
	if os.path.exists(_proto_dir):
		logger.error(f"Proto directory exists: {_proto_dir}")
		try:
			logger.error(f"Files in proto directory: {os.listdir(_proto_dir)}")
		except OSError as list_error:
			logger.error(f"Could not list proto directory: {list_error}")
	logger.error("Please run ./generate_proto.sh to generate the required files")
	logger.error(
		"Or ensure Docker build completed successfully (proto files are generated during build)"
	)
	raise ImportError("gRPC stubs missing or invalid; run ./generate_proto.sh from ai_demo/") from e

from handlers.rpc_handlers import RpcHandlers  # noqa: E402
from utils.grpc_worker_auth import WorkerAuthInterceptor, expected_token_from_env  # noqa: E402
from utils.log_redaction import redact_sensitive  # noqa: E402
from utils.rpc_rate_limit import check_rpc_rate_limit  # noqa: E402
from utils.validate_worker_env import WorkerEnvValidationError, validate_worker_env  # noqa: E402

# Import AI model service - gRPC adapter that calls local Ollama
try:
	from services.ai_model_service import AIModelService
	from services.host_profile_collector import collect_host_profile

	_ai_service = AIModelService()
	logger.info("AIModelService ready (Ollama model checked on health/preload)")
except ImportError as e:
	logger.warning("AIModelService not available: %s – Generate RPC will not work", e)
	_ai_service = None

	def collect_host_profile(_model_name=None):  # type: ignore[misc]
		return {}


def _grpc_message_size_options() -> list[tuple[str, int]]:
	max_bytes = 8 * 1024 * 1024
	return [
		("grpc.max_send_message_length", max_bytes),
		("grpc.max_receive_message_length", max_bytes),
	]


def _preload_model_blocking() -> bool:
	"""Load weights before accepting traffic (avoids OOM restart loop during background load)."""
	flag = os.getenv("MFAI_PRELOAD_MODEL", "1").strip().lower()
	if flag in ("0", "false", "no", "off"):
		return True
	if _ai_service is None:
		return False
	try:
		logger.info("Blocking preload of AI model (MFAI_PRELOAD_MODEL)")
		_ai_service.preload()
		logger.info("AI model ready for inference.")
		return True
	except Exception as exc:
		logger.error("Blocking model preload failed: %s", redact_sensitive(str(exc)))
		return False


class HealthServiceServicer(health_pb2_grpc.HealthServiceServicer):
	"""HealthService gRPC servicer — delegates to RpcHandlers (AI-UP2 Phase B)."""

	def __init__(self) -> None:
		self._handlers = RpcHandlers(lambda: _ai_service, health_pb2, collect_host_profile)

	@staticmethod
	def _rate_limited(method: str) -> tuple[bool, str]:
		return check_rpc_rate_limit(method)

	def HealthCheck(self, request, context):
		return self._handlers.health_check(request, context)

	def GetHostProfile(self, request, context):
		return self._handlers.get_host_profile(request, context)

	def Generate(self, request, context):
		return self._handlers.generate(request, context)

	def GenerateStream(self, request, context):
		yield from self._handlers.generate_stream(request, context)

	def FetchPublicStats(self, request, context):
		return self._handlers.fetch_public_stats(request, context)

	def OperatorStatsChat(self, request, context):
		return self._handlers.operator_stats_chat(request, context)

	def ReviewContent(self, request, context):
		return self._handlers.review_content(request, context)

	def BuildFaceContextSnapshot(self, request, context):
		return self._handlers.build_face_context_snapshot(request, context)

	def ChatRiskScore(self, request, context):
		return self._handlers.chat_risk_score(request, context)

	def GenerateReport(self, request, context):
		return self._handlers.generate_report(request, context)

	def EmbedText(self, request, context):
		return self._handlers.embed_text(request, context)

	def ExplainDecision(self, request, context):
		return self._handlers.explain_decision(request, context)


def _model_status_payload() -> dict:
	"""Health JSON payload (used by tests and admin probes)."""
	return RpcHandlers(
		lambda: _ai_service, health_pb2, collect_host_profile
	)._model_status_payload()


def serve():
	"""
	Start the gRPC server.

	The server listens on the port specified by the PORT environment variable,
	or defaults to 50051 if not set.
	"""
	try:
		validate_worker_env()
	except WorkerEnvValidationError as exc:
		logger.error("Worker environment validation failed: %s", exc)
		sys.exit(1)

	port = os.getenv("PORT", "50051")
	server_address = f"0.0.0.0:{port}"

	logger.info(f"Starting gRPC server on {server_address}")

	server_options = [
		("grpc.keepalive_permit_without_calls", 1),
		("grpc.http2.min_ping_interval_without_data_ms", 20000),
		("grpc.http2.min_recv_ping_interval_without_data_ms", 20000),
		*_grpc_message_size_options(),
	]
	interceptors = []
	worker_token = expected_token_from_env()
	if worker_token:
		interceptors.append(WorkerAuthInterceptor(worker_token))
		logger.info("AI worker gRPC auth enabled (AI_WORKER_EXPECTED_TOKEN)")
	server = grpc.server(
		futures.ThreadPoolExecutor(max_workers=10),
		interceptors=interceptors,
		options=server_options,
	)

	health_pb2_grpc.add_HealthServiceServicer_to_server(HealthServiceServicer(), server)

	cert_file = os.getenv("GRPC_TLS_CERT_FILE", "").strip()
	key_file = os.getenv("GRPC_TLS_KEY_FILE", "").strip()
	if cert_file and key_file:
		with open(cert_file, "rb") as cert_fp:
			cert_chain = cert_fp.read()
		with open(key_file, "rb") as key_fp:
			private_key = key_fp.read()
		credentials = grpc.ssl_server_credentials([(private_key, cert_chain)])
		server.add_secure_port(server_address, credentials)
		logger.info("gRPC TLS enabled (GRPC_TLS_CERT_FILE / GRPC_TLS_KEY_FILE)")
	else:
		server.add_insecure_port(server_address)
		if os.getenv("MFAI_ALLOW_INSECURE_GRPC", "").strip():
			logger.warning("gRPC listening on insecure port (MFAI_ALLOW_INSECURE_GRPC)")

	if not _preload_model_blocking():
		logger.warning(
			"Starting gRPC without a loaded model — HealthCheck will report unavailable."
		)

	server.start()
	logger.info(f"gRPC server started on {server_address}")

	try:
		server.wait_for_termination()
	except KeyboardInterrupt:
		logger.info("Shutting down server...")
		server.stop(0)
		logger.info("Server stopped")


if __name__ == "__main__":
	serve()
