#!/usr/bin/env python3
"""
server.py - gRPC server for AI Demo service

This server provides a health check endpoint via gRPC.
The server listens on port 50051 by default (configurable via PORT environment variable).

Usage:
    python server.py
    or
    ./server.py
"""

import os
import sys
import logging
from concurrent import futures

import grpc

# Configure logging FIRST, before any other imports that might use logger
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# Get the directory where this script is located
# Use absolute path to ensure we get the correct directory
script_path = os.path.abspath(__file__)
app_dir = os.path.dirname(script_path)

# Add app directory to Python path to allow imports
# This ensures that proto/ directory can be imported as a package
if app_dir not in sys.path:
    sys.path.insert(0, app_dir)

# Change to app directory to ensure relative imports work correctly
# This is important for Python to find the proto package
# Use absolute path to avoid issues with relative paths
os.chdir(os.path.abspath(app_dir))

# Import generated gRPC code
# These files are generated by generate_proto.sh from proto/health.proto
# They are also generated during Docker build in Dockerfile.dev
# The files are generated into proto/ directory, so we import from proto package
# proto/__init__.py is created in Dockerfile to make it a Python package

# Debug: Log current state before import
logger.debug(f"Python path: {sys.path[:3]}")
logger.debug(f"Current directory: {os.getcwd()}")
logger.debug(f"App directory: {app_dir}")

try:
    # First, try to import proto package to verify it exists
    import proto
    logger.debug(f"Proto package found at: {proto.__file__}")
    
    # Import from proto package (files are in proto/ directory)
    import proto.health_pb2 as health_pb2
    import proto.health_pb2_grpc as health_pb2_grpc
    logger.info("Successfully imported gRPC code from proto package")
except ImportError as e:
    logger.error(f"Failed to import generated gRPC code: {e}")
    logger.error(f"Exception type: {type(e).__name__}")
    logger.error(f"Python path: {sys.path}")
    logger.error(f"Current directory: {os.getcwd()}")
    logger.error(f"App directory: {app_dir}")
    # Try to list proto directory contents for debugging
    proto_dir = os.path.join(app_dir, 'proto')
    if os.path.exists(proto_dir):
        logger.error(f"Proto directory exists: {proto_dir}")
        try:
            files = os.listdir(proto_dir)
            logger.error(f"Files in proto directory: {files}")
        except Exception as list_error:
            logger.error(f"Could not list proto directory: {list_error}")
    logger.error("Please run ./generate_proto.sh to generate the required files")
    logger.error("Or ensure Docker build completed successfully (proto files are generated during build)")
    sys.exit(1)


class HealthServiceServicer(health_pb2_grpc.HealthServiceServicer):
    """
    Implementation of the HealthService gRPC service.
    
    This class handles health check requests from clients.
    """
    
    def HealthCheck(self, request, context):
        """
        Health check RPC method.
        
        This method is called when a client requests a health check.
        It returns a success response if the server is running and ready.
        
        Args:
            request: HealthCheckRequest message (currently unused)
            context: gRPC context
            
        Returns:
            HealthCheckResponse with status="success" if server is operational
        """
        logger.info("Health check requested")
        
        # Return success response indicating server is running and ready
        return health_pb2.HealthCheckResponse(
            status="success",
            message="AI Demo service is running and ready"
        )


def serve():
    """
    Start the gRPC server.
    
    The server listens on the port specified by the PORT environment variable,
    or defaults to 50051 if not set.
    """
    # Get port from environment variable or use default
    port = os.getenv('PORT', '50051')
    server_address = f'0.0.0.0:{port}'
    
    logger.info(f"Starting gRPC server on {server_address}")
    
    # Create gRPC server with thread pool executor
    # max_workers: number of threads to handle concurrent requests
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=10))
    
    # Add HealthService to the server
    health_pb2_grpc.add_HealthServiceServicer_to_server(
        HealthServiceServicer(), server
    )
    
    # Add insecure port (for development - use TLS in production)
    server.add_insecure_port(server_address)
    
    # Start the server
    server.start()
    logger.info(f"gRPC server started on {server_address}")
    
    try:
        # Keep the server running
        server.wait_for_termination()
    except KeyboardInterrupt:
        logger.info("Shutting down server...")
        server.stop(0)
        logger.info("Server stopped")


if __name__ == '__main__':
    serve()
